### ISSUE TITLE
Can't send to server 

### ISSUE THREAD

**Issue by yinkyAde** [lamisplus/central-sync-client#3]
Testing out the client sync new release v 2.2.2 i encountered an issue while trying to send to server 

**Sample Error Message**

Error sending data: 500: [
    <Map><timestamp>2024-04-03 T13: 10: 19.794+00: 00</timestamp><status>500</status><error>Internal Server Error</error><message></message><path>/api/v1/sync/receive-data/IiIYrVsq9rk/1 ae64958-5 f00-4e5 f-a2d8-0 a1f8cd5dd6b/7743 c46b-e78d-4 b9b-a54d-8177 f5872ded/hiv_art_pharmacy_regimens_10_20240403134000.json</path></Map>
]

Error sending data: 500: [
    <Map><timestamp>2024-04-03 T13: 10: 40.370+00: 00</timestamp><status>500</status><error>Internal Server Error</error><message></message><path>/api/v1/sync/receive-data/IiIYrVsq9rk/1 ae64958-5 f00-4e5 f-a2d8-0 a1f8cd5dd6b/e535d355-9233-4 a78-8 d63-b199e672207d/patient_encounter_0_20240403134000.json</path></Map>
]

**Sample Error Message from Stacktrace**

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [<Map><timestamp>2024-04-03T13:10:40.370+00:00</timestamp><status>500</status><error>Internal Server Error</error><message></message><path>/api/v1/sync/receive-data/IiIYrVsq9rk/1ae64958-5f00-4e5f-a2d8-0a1f8cd5dd6b/e535d355-9233-4a78-8d63-b199e672207d/patient_encounter_0_20240403134000.json</path></Map>]

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [<Map><timestamp>2024-04-03T13:10:38.746+00:00</timestamp><status>500</status><error>Internal Server Error</error><message></message><path>/api/v1/sync/receive-data/IiIYrVsq9rk/1ae64958-5f00-4e5f-a2d8-0a1f8cd5dd6b/120f6485-f9f7-4835-9a97-c89c7a6cf0ab/patient_visit_0_20240403134000.json</path></Map>]

**Comment by Mathew77** [comment]
Hi Israel, thank you for the feedback. The team will check and revert.
